import type { Metadata } from 'next'

import { Noto_Sans } from 'next/font/google'

import { cn } from '@/lib/utils'

import '@/styles/globals.css'

const notoSans = Noto_Sans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='pt-br' className={cn('dark font-sans', notoSans.variable)}>
      <body className='flex min-h-full flex-col'>{children}</body>
    </html>
  )
}
